#pragma once

// Checking input correctness
#define CHECKING_INPUT_CORRECTNESS_OPTION_SIZE 1
#define CHECKING_INPUT_CORRECTNESS_OPTION_INDEX 0
#define CHECKING_INPUT_CORRECTNESS_CORRECT_INPUT true
#define CHECKING_INPUT_CORRECTNESS_INCORRECT_INPUT false
#define CHECKING_INPUT_CORRECTNESS_INCORRECT_INPUT_DISPLAY "\nINVALID INPUT! PLEASE INPUT ONLY OPTIONS IN [...]\n\n"


// Main Menu options
#define MAIN_MENU_PRESS_DISPLAY "PRESS ["
#define MAIN_MENU_FOOTER_DISPLAY "\n"

// -> start new game
#define MAIN_MENU_START_NEW_GAME_DISPLAY "] TO START NEW GAME\n"
#define MAIN_MENU_START_NEW_GAME_KEYCAP '1'

// -> quit the game
#define MAIN_MENU_QUIT_DISPLAY "] TO QUIT\n"
#define MAIN_MENU_QUIT_THE_GAME_KEYCAP 'q'


// Players
#define MAX_PLAYER_NUMBER_SINGLE_GAME 2
#define DEFAULT_ID_PLAYER_1 1
#define DEFAULT_ID_PLAYER_2 2
#define DEFAULT_NAME_PLAYER_1 "Player 1"
#define DEFAULT_NAME_PLAYER_2 "Player 2"
#define TURN_DETERMINANT 2

// Changing the name of the player
#define PLAYER_CHANGE_THE_NAME_KEYCAP 'y'
#define PLAYER_DO_NOT_CHANGE_THE_NAME_KEYCAP 'n'
#define PLAYER_NAME_MAX_LENGTH 20

// Colours
#define BLACK_COLOUR_KEYCAP 'b'
#define BLACK_COLOUR_NAME "BLACK"
#define RED_COLOUR_KEYCAP 'r'
#define RED_COLOUR_NAME "RED"


// Board display
#define BOARD_WIDTH 43
#define BOARD_WIDTH_OPERATIONAL BOARD_WIDTH
#define BOARD_HEIGHT 20
#define BOARD_HEIGHT_OPERATIONAL BOARD_HEIGHT - 1

#define BOARD_COLUMN_NUMBER_DISPLAY_MULTIPLIER 5
#define BOARD_COLUMN_NUMBER_DISPLAY_SUBTRACTOR 2
#define BOARD_COLUMN_NUMBER_BUFFER_SIZE 1
#define BOARD_COLUMN_WIDTH 6
#define BOARD_COLUMN_CENTER_INDEX 3
#define BOARD_COLUMN_EDGE_INDEX 0
#define BOARD_COLUMN_EDGE_BUFFER_SIZE 1

#define BOARD_ROW_DIVIDER_INDEX 3

#define BOARD_COLUMN_NUMBER_BUFFER_SYMBOL ' '
#define BOARD_COLUMN_EDGE_BUFFER_SYMBOL ' '
#define BOARD_COLUMN_DIVISOR_BUFFER_SYMBOL ' '
#define BOARD_COLUMN_CORNER_SYMBOL '+'
#define BOARD_COLUMN_EDGE_SYMBOL '|'
#define BOARD_COLUMN_BOTTOM_SYMBOL '-'
#define BOARD_COLUMN_TOP_SYMBOL ' '

#define BOARD_ROW_DIVIDER_SYMBOL '+'

#define BOARD_HEADER "\nTHE BOARD\n\n"
#define BOARD_FOOTER "\n"

//game events
#define QUIT_THE_GAME_KEYCAP 'q'

#define CASTING_TO_CHAR '0'

#define DRAW_EVENT_DESCRIPTION "DRAW! NOBODY WINS THIS TIME :(\n"


// Field properties
#define ROWS_NUMBER 6
#define COLUMNS_NUMBER 7

#define Y_DIVISOR_INCREMENT 3
#define X_DIVISOR_INCREMENT 3

#define FIELD_UNOCCUPIED_SYMBOL ' '
#define FIELD_OCCUPIED_SYMBOL_BLACK 'U'
#define FIELD_OCCUPIED_SYMBOL_RED '^'