#pragma once

// Checking input correctness
#define CHECKING_INPUT_CORRECTNESS_OPTION_SIZE 1
#define CHECKING_INPUT_CORRECTNESS_OPTION_INDEX 0
#define CHECKING_INPUT_CORRECTNESS_CORRECT_INPUT true
#define CHECKING_INPUT_CORRECTNESS_INCORRECT_INPUT false
#define CHECKING_INPUT_CORRECTNESS_INCORRECT_INPUT_DISPLAY "\nINVALID INPUT! PLEASE INPUT ONLY OPTIONS IN [...]\n\n"


// Main Menu options
#define MAIN_MENU_FOOTER_DISPLAY "\n"

// -> start new game
#define MAIN_MENU_START_NEW_GAME_DISPLAY "PRESS [" << MAIN_MENU_START_NEW_GAME_KEYCAP << "] TO START NEW GAME\n"
#define MAIN_MENU_START_NEW_GAME_KEYCAP 's'

// -> quit the game
#define MAIN_MENU_QUIT_DISPLAY "PRESS [" << MAIN_MENU_QUIT_THE_GAME_KEYCAP << "] TO QUIT\n"
#define MAIN_MENU_QUIT_THE_GAME_KEYCAP 'q'


// Players
#define PLAYER_MAX_NUMBER_PER_GAME 2
#define PLAYER_ID_INCREMENT 1

#define PLAYER_DEFAULT_ID_1 1
#define PLAYER_DEFAULT_ID_2 2
#define PLAYER_DEFAULT_NAME_1 "Player 1"
#define PLAYER_DEFAULT_NAME_2 "Player 2"

// -> choose the colour
#define PLAYER_CHOOSE_COLOUR_PLAYER_DISPLAY "\n<PLAYER "
#define PLAYER_CHOOSE_COLOUR_DISPLAY ">\nPRESS OPTION IN [...] TO CHOOSE THE COLOUR\n"
#define PLAYER_CHOOSE_COLOUR_BLACK_AVAILABLE_DISPLAY "BLACK [" << COLOUR_BLACK_KEYCAP << "] - STARTS THE GAME\n"
#define PLAYER_CHOOSE_COLOUR_BLACK_UNAVAILABLE_DISPLAY "BLACK [] - STARTS THE GAME (UNAVAILABLE)\n"
#define PLAYER_CHOOSE_COLOUR_RED_AVAILABLE_DISPLAY "RED [" << COLOUR_RED_KEYCAP << "] - MOVES SECOND\n"
#define PLAYER_CHOOSE_COLOUR_RED_UNAVAILABLE_DISPLAY "RED [] - MOVES SECOND (UNAVAILABLE)\n"
#define PLAYER_CHOOSE_COLOUR_FOOTER_DISPLAY "\n"

#define PLAYER_CHOOSE_COLOUR_TAKEN_COLOUR_INDEX 0

// -> Colours
#define COLOUR_BLACK_NAME "BLACK"
#define COLOUR_BLACK_KEYCAP 'b'
#define COLOUR_RED_NAME "RED"
#define COLOUR_RED_KEYCAP 'r'

// -> change the name of the player
#define PLAYER_NAME_CHANGE_CHANGE_THE_NAME_DISPLAY "\nPRESS [" << PLAYER_NAME_CHANGE_CHANGE_THE_NAME_KEYCAP << "] TO SET THE PLAYER NAME\n"
#define PLAYER_NAME_CHANGE_CHANGE_THE_NAME_KEYCAP 's'
#define PLAYER_NAME_CHANGE_DO_NOT_CHANGE_THE_NAME_DISPLAY "PRESS [" << PLAYER_NAME_CHANGE_DO_NOT_CHANGE_THE_NAME_KEYCAP << "] TO USE DEFAULT PLAYER NAME\n"
#define PLAYER_NAME_CHANGE_DO_NOT_CHANGE_THE_NAME_KEYCAP 'd'
#define PLAYER_NAME_CHANGE_FOOTER_DISPLAY "\n"

// -> set new player name
#define PLAYER_NAME_CHANGE_SET_NAME_DISPLAY "\nSET THE PLAYER NAME\n\n"
#define PLAYER_NAME_CHANGE_INVALID_NAME_LENGTH_DISPLAY "\nPROVIDED NAME IS TOO LONG! [MAXIMUM LENGTH OF THE PLAYER NAME IS " << PLAYER_NAME_CHANGE_NAME_MAX_LENGTH << " CHARACTERS]\n"
#define PLAYER_NAME_CHANGE_NEW_NAME_DISPLAY "\nTHE NEW PLAYER NAME WAS ASSIGNED <"
#define PLAYER_NAME_CHANGE_DEFAULT_NAME_DISPLAY "\nDEFAULT PLAYER NAME WAS ASSIGNED <"
#define PLAYER_NAME_CHANGE_SET_NAME_FOOTER_DISPLAY ">\n"

#define PLAYER_NAME_CHANGE_NAME_MAX_LENGTH 20


// Field properties
#define ROWS_NUMBER 6
#define COLUMNS_NUMBER 7

#define FIELD_Y_DIVISOR_INCREMENT 3
#define FIELD_X_DIVISOR_INCREMENT 3
#define FIELD_INDEX_INCREMENT 1

#define FIELD_UNOCCUPIED_SYMBOL ' '
#define FIELD_OCCUPIED_SYMBOL_BLACK 'U'
#define FIELD_OCCUPIED_SYMBOL_RED '^'


// Board display
#define BOARD_HEADER "\nTHE BOARD\n\n"
#define BOARD_FOOTER "\n"

#define BOARD_WIDTH 43
#define BOARD_WIDTH_OPERATIONAL BOARD_WIDTH
#define BOARD_HEIGHT 20
#define BOARD_HEIGHT_OPERATIONAL BOARD_HEIGHT - 1

#define BOARD_COLUMN_NUMBER_DISPLAY_MULTIPLIER 5
#define BOARD_COLUMN_NUMBER_DISPLAY_SUBTRACTOR 2
#define BOARD_COLUMN_NUMBER_BUFFER_SIZE 1
#define BOARD_COLUMN_WIDTH 6
#define BOARD_COLUMN_CENTER_INDEX 3
#define BOARD_COLUMN_EDGE_INDEX 0
#define BOARD_COLUMN_EDGE_BUFFER_SIZE 1

#define BOARD_ROW_DIVIDER_INDEX 3

#define BOARD_COLUMN_NUMBER_BUFFER_SYMBOL ' '
#define BOARD_COLUMN_EDGE_BUFFER_SYMBOL ' '
#define BOARD_COLUMN_DIVISOR_BUFFER_SYMBOL ' '
#define BOARD_COLUMN_CORNER_SYMBOL '+'
#define BOARD_COLUMN_EDGE_SYMBOL '|'
#define BOARD_COLUMN_BOTTOM_SYMBOL '-'
#define BOARD_COLUMN_TOP_SYMBOL ' '

#define BOARD_ROW_DIVIDER_SYMBOL '+'
#define BOARD_ROW_SEPARATOR '\n'


// Main game loop
#define TURN_DETERMINANT 2
#define CASTING_TO_CHAR '0'

// -> for every turn
#define TURN_COLOUR_DISPLAY "TURN OF THE (" 
#define TURN_PLAYER_DISPLAY ") PLAYER <"
#define TURN_FOOTER_DISPLAY ">\n"
#define TURN_POSSIBLE_MOVES_DISPLAY "POSSIBLE MOVES: \n"
#define TURN_AVAILABLE_COLUMN_DISPLAY "COLUMN ["
#define TURN_AVAILABLE_COLUMN_FOOTER_DISPLAY "]\n"
#define TURN_QUIT_TO_MAIN_MENU_DISPLAY "QUIT [" << TURN_QUIT_TO_MAIN_MENU_KEYCAP << "]\n\n"
#define TURN_QUIT_TO_MAIN_MENU_KEYCAP 'q'
#define TURN_QUIT_TO_MAIN_MENU_PLAYER_DISPLAY "\nPLAYER <"
#define TURN_QUIT_TO_MAIN_MENU_DESCRIPTION_DISPLAY "> QUIT THE GAME\n\n"

// -> in case of victory
#define WIN_EVENT_PLAYER_DISPLAY "PLAYER <"
#define WIN_EVENT_COLOUR_DISPLAY "> WHO PLAYED ("
#define WIN_EVENT_FOOTER_DISPLAY ") WINS!\n\n"

// -> in case of a draw
#define DRAW_EVENT_DESCRIPTION_DISPLAY "NO MOVES AVAILABLE!\n\nDRAW! NOBODY WINS THIS TIME :(\n\n"
